spring:
  profiles:
    active: dev
---
spring:
  profiles: default
server:
  port: 8082
expo:
  driver: com.microsoft.sqlserver.jdbc.SQLServerDriver
  url: jdbc:sqlserver://YORCH\SQLEXPRESS;databaseName=Expo
  user: gaslissa_app
  pwd: $Gaslissa.2k9!
  